### ISSUE TITLE
I have conflicts...now what?

### ISSUE THREAD

**Issue by dmrickey** [mouse0270/module-credits#18]
![image](https://user-images.githubusercontent.com/3664822/152599292-d1571ee6-47b5-4b77-8f70-4418f34c3920.png)

I don't see anything anywhere that tells me what these conflicts are, so I have no info to move forward with.

**Comment by mouse0270** [comment]
You should have something like this next to the modules name
![image](https://user-images.githubusercontent.com/564874/152603082-68f174ec-bbf1-4a24-b0d4-1d28f93b0a1c.png)
hovering over it will tell you about the conflict.

**Comment by mouse0270** [comment]
If you don't have that little icon next to anything, please send me a list of all of your modules?

**Comment by mouse0270** [comment]
If you update, I have included the ability to display some logs to help find this issue more, if you would like, please feel free to contact me on discord at Mouse0270#0270 or here and I will try to get all of this resolved for you.

**Comment by dmrickey** [comment]
> You should have something like this next to the modules name ![image](https://user-images.githubusercontent.com/564874/152603082-68f174ec-bbf1-4a24-b0d4-1d28f93b0a1c.png) hovering over it will tell you about the conflict.

Oh I didn't notice that icon on the left at all. I put a breakpoint on the new debug line and had to inspect the conflicts to know which ones to checked. That icon just blends into the title because it's the same color as the text--I was I expecting a red circle or an red exclamation point or something to match the icon pictured above.

I've got "3" now. It would be nice if these were smarter. For instance, I've got a warning for "Tidy UI" which I don't have enabled, I've got a warning for "module credits^tidy-ui" which again I don't have Tidy UI enabled, and I've got one for "module credits^lib-changelogs" which I don't have "lib-changelogs" at all. It makes sense to show those in the module management window. But it's pretty alarming to see a big red "conflicts: 3" on the "Manage Modules" button--especially when I basically don't have any active conflicts

**Comment by mouse0270** [comment]
The lib-changelogs is an actual bug, its only supposed to register if both modules are enabled. It appears I broke that logic and its not taking that into account, I will look into that first thing in the morning. So it should really only report 2 conflicts.

I can review the UI display, the problem is, it gets really complicated to track both the conflicts and the conflicts that are active. I'd be looping through data a few times and having it always show was just a simple way to keep it light weight. But I can see the confusion where the current UI makes it seem like you have an active conflict/issue with your "active" modules. When in reality, its just conflicts with just your "installed" modules.

Do you have a suggestion to make the counting more clear? Because I honestly have know idea how I would improve that design without cluttering up the interface more.

**Comment by mouse0270** [comment]
```
}else if (conflict.type != 'foundry' && (game.modules.get(conflict?.name) ?? false)) {
```
Awe this broke when I added the ability to check conflicts with foundry and I forgot to add the check to see if the conflicting module existed if the type isn't foundry... `&& (game.modules.get(conflict?.name) ?? false)`

**Comment by mouse0270** [comment]
I just pushed v1.1.6 which should stop lib-changelogs from registering as a conflict in your module list.

Which means this is down to UI and more clarity on what information is being displayed, correct?

**Comment by mouse0270** [comment]
In the current release
