### ISSUE TITLE
preset fails to save, just hangs

### ISSUE THREAD

**Issue by wmve** [mouse0270/module-credits#42]
when i type in "newtest" and hit the save button, it seems to hang

![image](https://user-images.githubusercontent.com/55966777/175827695-ea5633bb-193f-4c2d-ba8c-ae729a492106.png)

and i see this message in the log

![image](https://user-images.githubusercontent.com/55966777/175827708-18539f6e-caf5-41f3-b9f4-947208bd5efe.png)

the preset is never created.  if i exit the dialog and come back later it's not listed.

**Comment by mouse0270** [comment]
This is less of a bug and more of an issue with local storage being out of space. 

The problem here is that if I make the setting a `world` setting then the presets only exist in one single world, so they are a client setting. I will look to see if I can resolve this another way. Maybe create a local database to store the values in. Though that may have issues with certain hosting environments
