### ISSUE TITLE
Feature Request: optional modifier key effect on Disable All Modules

### ISSUE THREAD

**Issue by esheyw** [mouse0270/module-credits#56]
I'd love a way to quickly say 'deactivate all modules, except MM+', without having to make that an explicit preset cluttering the list. I often go down to zero modules to test things, but in most of those cases MM+ would not be a likely source of conflict, and leaving it enabled saves an entire world reload from the workflow (open MM, enable MM+, reload, open MM, apply preset, reload).

Maybe ctrl-click?

**Comment by mouse0270** [comment]
This was a feature from TidyUI, where they had a button for disabling everything but TidyUI. And to be honest, I really do miss it from MM+. 

Really the only reason it doesn't exist is UI/UX issues. I was trying to make the interface cleaner, so adding an extra button was a little much, and doing something like ctrl+click isn't intuitive.

It's a feature I'd like as oftentimes, I disable all modules, then go an enable MM+, then hit save, it would save me a click to have an option to leave MM+.

I wonder if I could make something like a default preset, that you can expand on that will always include MM+. For example, instead of clearing everything but MM+ with a specific button, you set a default preset. This would be useful for me, who's default preset is MM+, Dev Mode, Bug Reporter and Find the Culprit. 

I will look into this option, but I have to think about what I want and how to implement it. Do I want to an option to just disable everything but MM+, or an option that lets you define a default preset and it applies that. Maybe both options?

**Comment by mouse0270** [comment]
![image](https://user-images.githubusercontent.com/564874/192067711-e51e5455-0bb4-4d60-9bb2-6d1352f64281.png)

I think this is what I am going to go with. Where you can lock modules from being deactivated.

**Comment by mouse0270** [comment]
Included in v2.1.0
