### ISSUE TITLE
AutoPrefix not working correctly in some cases.

### ISSUE THREAD

**Issue by Oshcakes** [mouse0270/module-credits#65]
[Crucible Magazine | Issue #002 - Underworld](https://foundryvtt.s3.us-west-2.amazonaws.com/modules/crucible-mag-002/module-2.5.json)

![image](https://user-images.githubusercontent.com/61471647/192656235-921fdb5d-8933-45b6-9361-266cde558135.png)

Ends up looking like this:
![image](https://user-images.githubusercontent.com/61471647/192656256-3208f32b-85f0-406d-9ffe-035d18ec84e1.png)

**Comment by mouse0270** [comment]
I bet you that's working exactly as designed, now if thats good or not is really subjective.

What's happening is that [Crucible Magazine | Issue #002 - Underworld](https://foundryvtt.s3.us-west-2.amazonaws.com/modules/crucible-mag-002/module-2.5.json) has a lot of requirements and all `Auto Prefix` does is append all requirements to the start of the module title.

Is that a good thing? Well clearly from the looks of that... Not really. I am open to suggestions on what you would expect the Auto Prefix to do instead.

A few things you could do now to minimize the issue is to do one of the following
1. Disable Auto Prefix
2. Right Click and Rename the Module

Honestly if I could, Id try to get the tags from Foundry's site and use those, but that would require me pinging against their website quite a bit and I dont think they would like that.

Maybe add a limitation to how many things can be prefixed? But what should I limit it to? 1 prefix, 2 prefixes, how do I choose which thing to prefix over another?

This is kind of a tough thing to solve... Cause it mostly just guess work and not everyone is going to agree. I mean I could even add smart tags so that if the module name starts with `Crucible Magazine` it gets prefix with `Content Pack - `

As I said, if you have a suggestion on what behavior you expected, I am happy to hear you out.

**Comment by mouse0270** [comment]
Here is my idea:
![image](https://user-images.githubusercontent.com/564874/192691093-482c71fd-5eb9-43f3-81d6-e300f55a8169.png)

Instead of prefix every single module requirement, instead I will just add a little arrow showing that this has been placed outside of its normal sort order.

In the case of [Crucible Magazine | Issue #002 - Underworld](https://foundryvtt.s3.us-west-2.amazonaws.com/modules/crucible-mag-002/module-2.5.json) This would still get placed under `Compendium Folders` but its a requirement, so the script will think its supposed to group them.

**Comment by mouse0270** [comment]
AutoPrefixing labels has been replaced with smart Labels, this should help clean up this issue.

v2.1.4

**Comment by Oshcakes** [comment]
Oh yeah thats the sauce. thankls!
