### ISSUE TITLE
Settings tab has build and active module number hidden

### ISSUE THREAD

**Issue by M0nk3yy** [mouse0270/module-credits#88]
I presume this is deliberate but think it would be best to stick with the core setup. 

Core:

![image](https://user-images.githubusercontent.com/66137312/208729618-f44dcb83-1d5c-49f6-9ae0-65b5ecaa8efc.png)

Module Management+ active:

![image](https://user-images.githubusercontent.com/66137312/208729870-b7493c22-590a-40f4-b01b-557472116d14.png)

**Comment by mouse0270** [comment]
This was deliberate but is also a bug #66 As I meant to include it in the button text as an alternative place here.

As a side note, it's just a generally a bad idea to use the argument
> best to stick with the core setup.

Because if your argument is, do it like core does it, then there is no reason to install modules... I assume you meant, Please provide a way to see the active module count. Which will be in the next update, it got delayed because I am reworking the module for web accessibility and that was a bigger task then I initially thought.

**Comment by mouse0270** [comment]
Verison 2.1.6 Now has a setting to choose where to display active module count, it is hidden by default. As this is they way I want to use my module, this will be the default setting, however, your now able to enable it for how you would like it.
