### ISSUE TITLE
Modification To General Information Hides Important Information

### ISSUE THREAD

**Issue by tjlanza** [mouse0270/module-credits#92]
Your modification to the top of General Information section (as mentioned in https://github.com/mouse0270/module-credits/issues/66 and https://github.com/mouse0270/module-credits/issues/88) removes core functionality (module count and update notification) without providing any improved functionality. Despite [your argument](https://github.com/mouse0270/module-credits/issues/88#issuecomment-1360053443) in the other post, you appear to have made a change for change's sake without considering the full ramifications. Yes, modules are a way to make things better. Your proposed changes make things less functional.

Without MM+ 2.1.5
![image](https://user-images.githubusercontent.com/21128724/222267066-ca9e7016-61ee-428f-b76a-430dabf77b96.png)

With MM+ 2.15
![image](https://user-images.githubusercontent.com/21128724/222267370-ce0d83d7-deda-4e05-9ec9-a01a4bb2a4ee.png)

**Comment by mouse0270** [comment]
Alright, so to be clear, the functionality I broke is two things correct:

Removed Active Module Count which I have stated in both #66 and #88 is technically a bug as I intended to move them down to the button but never did, cause honestly its data I never cared about in the first place. But either way my intention was to never remove functionality, just move it around a bit. 

But how does my proposed changes of moving the count to the button instead of under the Game make it less functional. It not being there for sur make it less functional, but as stated, that is an oversight and not the intended purpose, meaning Bug.

Now as to why I adjusted that section of the window was because I wanted to slim it down because I add buttons for the system to that section, So I purposely condensed the versioning and removed the modules to make room for when I add the buttons, Readme, Changelog and Attributions for the system under that section.

**Comment by tjlanza** [comment]
Combining Foundry's version and build number into one line makes sense - no information is lost, and it's roughly in the same place.

If the goal is to save space, removing the horizontal rule would accomplish that. It's a meaningful separator when the Foundry data is split across two lines, but you've combined those two lines, so now it's just taking up space.

I disagree that moving the module count down from the expected place is a significant or worthwhile improvement to the user interface or user experience. There's no strongly compelling reason to move it.

**Comment by mouse0270** [comment]
See your major issue is that I removed active modules because I wanted to move them down to the button, and then completely forgot that was even apart of the interface. To me, seeing the number of active modules is useless data and can be found on the Module Management window, which it makes more sense there than anywhere else.

There is no reason to know how many modules are active, it serves 0 purpose other than useless information. Knowing there is 29 active modules does nothing for you. Knowing what modules are active is useful and found under the Module Management window. Can you tell me a reason why seeing active modules at a quick glance is even remotely useful? What does knowing you have 13 or 29 or 103 modules active provide you? If you can give me a good answer that makes sense other than, "Its who core does it" Then you'll have a better chance of me understanding your side. Either way, I do plan to add the information back and if I am nice I will give the option for it to be displayed on the button or in its default location.

As for "significant or worthwhile improvement", I never said moving it down there was either of those things, I said, that's where I intended to put it.

Now, the update notification thing is an issue, and that Really needs to be fixed. I will make sure that is corrected.

**Comment by mouse0270** [comment]
Verison 2.1.6 Now has a setting to choose where to display active module count, it is hidden by default. As this is they way I want to use my module, this will be the default setting, however, your now able to enable it for how you would like it.

I also fixed the issue where the Update Notification was missing if Core or System were out of date.
